### ISSUE TITLE
PHP Fatal error:  Class Nuwira\Bandrek\Hasher contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Hashing\Hasher::info)

### ISSUE THREAD

**Issue by in10dev** [Nuwira/bandrek#1]
When you use the passwordforget function in laravel 5.6.7

**Comment by matriphe** [comment]
Thanks for the report. Will check it out in Laravel 5.6.

**Comment by fidovandenbos** [comment]
i have the solution how can i send it to you ?

**Comment by fidovandenbos** [comment]
`/**
     * Get information about the given hashed value.
     *
     * @param  string  $hashedValue
     * @return array
     */
    public function info($hashedValue)
    {
        return password_get_info($hashedValue);
    }
`

**Comment by matriphe** [comment]
@fidovandenbos it would be good if you can make a PR

**Comment by fidovandenbos** [comment]
@matriphe i have create a pull request

**Comment by matriphe** [comment]
@fidovandenbos thanks for the PR! 

@in10dev I've updated the package. Please do `composer update nuwira/bandrek` to update to version 1.1.0.
