### ISSUE TITLE
Password reset token not working

### ISSUE THREAD

**Issue by fidovandenbos** [Nuwira/bandrek#3]
When u use a numeric token for password reset, the token is not valid.

**Comment by fidovandenbos** [comment]
I have create a pull request for fixing the issue.

**Comment by fidovandenbos** [comment]
The test seems not to work, but i think there is a issue with the test. I have test is in real working system. there is the issue and its works fine with laravel version 5.6.7

**Comment by matriphe** [comment]
Thanks @fidovandenbos! The PR has been merged!
